MAX_TURNS_PER_PLAYER = 1

MIN_COMBAT_CARD = 2
MAX_COMBAT_CARD = 5
MAX_COMBAT_POWER = 7

MAX_POPULARITY = 18
MAX_POWER = 18

MIN_PLAYERS = 2
MAX_PLAYERS = 2

MAX_STARS = 6

BOARD_ROWS = 8
BOARD_COLS = 7

NUM_COMBAT_CARD_VALUES = 4
NUM_ENLIST_BENEFITS = 4
NUM_FACTIONS = 5
NUM_MECHS = 4
NUM_PIECE_TYPES = 4
NUM_PLAYER_MAT_ACTION_SPACES = 4
NUM_PLAYER_MATS = 5
NUM_RESOURCE_TYPES = 4
NUM_STAR_TYPES = 9
NUM_STRUCTURE_BONUSES = 6
NUM_STRUCTURES = 4
NUM_UPGRADE_CUBES = 6
NUM_WORKERS = 10

FACTORY_COORDS = (3, 3)

DECK_SIZE = 16 + 12 + 8 + 6

MAX_BOTTOM_ACTION_COST = 4
