from enum import Enum


class Head(Enum):
    VALUE_HEAD = 0
    OPTIONAL_HEAD = 1
    BOOLEAN_HEAD = 2
    MAYBE_PAY_COST_HEAD = 3
    BOARD_COORDS_HEAD = 4
    PIECE_TYP_HEAD = 5
    RESOURCE_TYP_HEAD = 6
    BOTTOM_ACTION_TYP_HEAD = 7
    ENLIST_REWARD_HEAD = 8
    MECH_TYP_HEAD = 9
    STRUCTURE_TYP_HEAD = 10
    CUBE_SPACE_HEAD = 11
    OPTIONAL_COMBAT_CARD_HEAD = 12
    WHEEL_POWER_HEAD = 13
    NUM_WORKERS_HEAD = 14
    NUM_RESOURCES_HEAD = 15
    CHOOSE_ACTION_SPACE_HEAD = 16
